name = "SDDGeometry"
uuid = "a6bfdfb4-bfc7-488f-8e1d-c7ae636f08ae"
authors = [
  "Renato Leriche Vázquez <r_lerichev@ciencias.unam.mx>",
  "Luis Muñiz",
  "Edgar Rodriguez",
  "Daniel Blancas"
]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
